/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/UnitTests/JUnit5TestClass.java to edit this template
 */
package com.mycompany.registrationandlogin;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

/**
 *
 * @author setlh
 */
public class SendingMessagesTest {
    
    public SendingMessagesTest() {
    }

    @Test
    public void testCheckMessageIDSuccess() {
          SendingMessages myObj =new SendingMessages("+27718693002","Hi Mike, can you join us for dinner tonight?");
        boolean expected=true;
        boolean actual=myObj.checkMessageID();
        assertEquals(expected,actual,"Message ready to send");
    }

     @Test
    public void testCheckMessageIDFailure() {
          SendingMessages myObj =new SendingMessages("+27718693002","Hi Mike, can you join us for dinner tonight?");
        boolean expected=true;
        boolean actual=myObj.checkMessageID();
        assertEquals(expected,actual,"Message exceeds 250 characters by X[enter number here];please reduce size");
    }
    
    @Test
    public void testCheckRecipientCellSuccess() {
           SendingMessages testMethod =new SendingMessages("+27718693002", "Hi Mike, can you join us for dinner tonight?");

        String expected = "Cell phone number successfully captured.";
        String actual = testMethod.checkRecipientCell();
        assertEquals(expected,actual);
    }

      @Test
    public void testCheckRecipientCellFalilure()
    {
        SendingMessages testMethod = new SendingMessages("08575975889","Hi Keegan, did you receive the payment?");
        String expected="Cell phone number is incorrectly formatted or does not contain an international code.";
        String actual=testMethod.checkRecipientCell();
        assertEquals(expected,actual);
    }
    
    @Test
    public void testAutogeneratedmessageHash() {
          SendingMessages testMethod =new SendingMessages("+27718693002","Hi Mike can you join us for dinner tonight");

        String actual= testMethod.autogeneratedmessageHash();
        assertTrue(actual.contains("HI"));
        assertTrue(actual.contains("TONIGHT"));
    }

    @Test
    public void testSentMessage() {
          SendingMessages testMethod=new SendingMessages("+27718693002", "Hi Mike, can you join us for dinner tonight?" );

        String expected ="Message successfully sent";
        String actual=testMethod.sentMessage(1);
        assertEquals(expected,actual);
        String expected2 ="Coming Soon.";
        String actual2=testMethod.sentMessage(2);
        assertEquals(expected2,actual2);
        String expected3 ="Quit";
        String actual3=testMethod.sentMessage(3);
        assertEquals(expected3,actual3);
    }

}
