/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package com.mycompany.registrationandlogin;

import java.util.Random;
import java.util.HashMap;
import java.io.FileWriter;
import java.io.IOException;

/**
 *
 * @author Setlhabe Tsedintle
 */
public class SendingMessages {
    private String uniqueMessageID;
    private  String recipient; 
    private  String messageLength;
    private String messageHash;
    private static int totalMessages = 0;
    private String option;
    private static String[] sentMessages = new String[100];
    
     //Constructor
    public SendingMessages(String recipient,String messageLength)
    {
        this.recipient=recipient;
        this.messageLength=messageLength;
        this.uniqueMessageID=generateduniqueMessageID();
        this.messageHash=autogeneratedmessageHash();
    }
    
    //A random ten digit to retrieve or delete message
    private String generateduniqueMessageID() 
    {
        Random newNum = new Random();
        StringBuilder messageID=new StringBuilder();
        for (int i = 0; i < 10; i++) 
        {
             messageID.append(newNum.nextInt(10));
           
        }
           String id=messageID.toString();
            return id;
    }
   
    //The checkMessageID() method checks whether the message ID is valid.
    public  boolean checkMessageID()
    {
       if(uniqueMessageID.length()<=10)
    {
        System.out.println("Message succesfully captured");
        return true;
    }
       else
       {
           System.out.println("Message exceed 250 characters ");
        return false;
       }
    }
    public  String checkRecipientCell()
    {
    if(recipient.matches("\\+27\\d{9}"))
    {
        return "Cell phone number successfully captured.";
    }
    else
    {
        return "Cell phone number is incorrectly formatted or does not contain an international code.";
    }
}
    
    public String autogeneratedmessageHash()
   {
       
        String startID = uniqueMessageID.substring(0, 2);
        int numMessage = messageLength.length();

        String[] shortMessage = messageLength.split(" ");
        String firstMessage = shortMessage[0];
        String lastMessage = shortMessage[shortMessage.length - 1];

        StringBuilder hash = new StringBuilder();

        hash.append(startID);
        hash.append(":");
        hash.append(totalMessages);
        hash.append(":");
        hash.append(firstMessage);
        hash.append(lastMessage);

       return hash.toString().toUpperCase();
    
   }
    
    //The sentMessage() method handles menu options.
   public String sentMessage(int option)
   {
     
       switch (option) {

        case 1:
            sentMessages[totalMessages] = messageLength;
            totalMessages++;
           storeMessage();

            return "Message successfully sent";

        case 2:
            return "Coming Soon.";

        case 3:
            return "Quit";

        default:
            return "Invalid option";
    }  
      
   
   }
   
  

   public String printMessage()
   {
          String allMessages = "";

    for(int i = 0; i < totalMessages; i++)
    {
        allMessages= sentMessages[i] ;
    }

    return allMessages;
         
   }
   
   public static int returnTotalMessages()
   {
       return totalMessages;
   }
   
   public void storeMessage()
   {
     
    {
    try
    {
        FileWriter writer = new FileWriter("message.json", true);

        writer.write("{\n");

        writer.write("\"MessageID\":\""+ uniqueMessageID + "\",\n");

        writer.write("\"Recipient\":\""+ recipient + "\",\n");

        writer.write("\"Message\":\""+ messageLength + "\"\n");

        writer.write("}\n");

        writer.close();

    }
    catch(IOException e)
    {
        System.out.println("Error storing message.");
    }
   }

   }
   
   
    // Getters
    public String getMessageID()
    {
        return uniqueMessageID;
    }
   
    public String getMessageHash() 
    {
         return messageHash;
    }
   
    public String getRecipient() 
    {
        return recipient;
    }
   
    public String getMessageLenth() {
         return messageLength;
        
    }
   
}

